---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luxizhu.
--- DateTime: 2021/5/31 10:33
---

local require = require
local const = require "kuab.kdgp.const"
local util = require "kuab.util.util"
local setmetatable = setmetatable
local table = table
local tostring = tostring
local itoa = util.itoa

---
---@field head_length number
---@field body_length number
---@field crc string
---@field head_data string
---@field body_data string
---@class packet_t
local _M = {}

function _M:fill_crc(session_token)
    self.crc = util.CalcCrc(tostring(self), session_token)
    return self
end

function _M:toString()
    local head_data = tostring(self.head_data)
    local body_data = tostring(self.body_data)
    local head_length = #head_data + const.kCRCFieldLen + const.kHeadFormatFieldLen
    local body_length = #body_data + const.kBodyFormatFieldLen
    local crc = self.crc or "00000000"
    return table.concat {
        "KDGP",
        itoa(head_length),
        itoa(body_length),
        crc,
        "KDGB",
        head_data,
        "JSTB",
        body_data
    }
end

function _M.new(t)
    return setmetatable(t, {
        __index = _M,
        __tostring = _M.toString
    })
end

return _M