---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luxizhu.
--- DateTime: 2021/5/31 13:40
---

local require = require
local setmetatable = setmetatable
local tostring = tostring
local kdgp_packet = require "kuab.kdgp.packet"
local _M = {}

function _M.apply(self)
    local head_data = tostring(self.head_builder())
    local body_data = tostring(self.body_builder())
    return kdgp_packet.new {
        head_data = head_data,
        body_data = body_data,
        Context = self.head_builder.Context,
    }
end

function _M.new(head_builder, body_builder)
    local self = {
        head_builder = head_builder,
        body_builder = body_builder,
    }
    local mt = {
        __index = _M,
        __call = _M.apply,
    }
    return setmetatable(self, mt)
end

return _M