---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luxizhu.
--- DateTime: 2021/5/31 15:30
---

---@class CodecStatus
return {
    -- 解码失败
    CODEC_FAIL = -1,

    -- 解码成功
    CODEC_OK = 0,

    -- 解码尚未完成
    CODEC_CONTINUE = 1
}